from app.schemas.job_search import JobListing
from app.services.job_providers.base_provider import BaseJobProvider


class AggregatorJobProvider(BaseJobProvider):
    @property
    def provider_name(self) -> str:
        return "UK & Global Career Hub"

    async def fetch_jobs(self, query: str | None, location: str | None, work_mode: str | None) -> list[JobListing]:
        catalog = [
            # 1. DeepMind
            JobListing(
                id="uk_ds_101",
                title="Graduate Data Scientist & ML Associate",
                company="DeepMind",
                company_domain="deepmind.google",
                company_logo_url="https://www.google.com/s2/favicons?domain=deepmind.google&sz=128",
                location="London, United Kingdom",
                country="United Kingdom",
                city="London",
                work_mode="ONSITE",
                employment_type="Full-time",
                experience_level="Entry Level",
                salary="£70,000 - £95,000 / year",
                description="Entry-level Data Scientist opportunity in London for graduates passionate about frontier AI, deep learning, PyTorch, statistical modeling, and Python data pipelines.",
                url="https://deepmind.google/careers",
                source_url="https://deepmind.google/careers",
                apply_url="https://deepmind.google/careers",
                posted_date="1 hour ago",
                source="DeepMind Careers",
                source_job_id="deepmind_ds_101",
                skills=["Python", "Data Science", "Machine Learning", "PyTorch", "SQL", "Git", "Statistical Modeling"],
                is_external_application=True
            ),
            # 2. Revolut
            JobListing(
                id="uk_swe_102",
                title="Software Engineer - Python & Distributed Systems",
                company="Revolut",
                company_domain="revolut.com",
                company_logo_url="https://www.google.com/s2/favicons?domain=revolut.com&sz=128",
                location="London, United Kingdom",
                country="United Kingdom",
                city="London",
                work_mode="HYBRID",
                employment_type="Full-time",
                experience_level="Mid Level",
                salary="£85,000 - £115,000 / year",
                description="Revolut is hiring a Software Engineer to build high-throughput financial backend services using Python, FastAPI, PostgreSQL, Docker, and Kubernetes.",
                url="https://revolut.com/careers",
                source_url="https://revolut.com/careers",
                apply_url="https://revolut.com/careers",
                posted_date="2 hours ago",
                source="Revolut Careers",
                source_job_id="revolut_swe_102",
                skills=["Python", "FastAPI", "PostgreSQL", "Docker", "Kubernetes", "Redis", "Microservices"],
                is_external_application=True
            ),
            # 3. Monzo
            JobListing(
                id="uk_swe_103",
                title="Backend Developer (Python & Go)",
                company="Monzo Bank",
                company_domain="monzo.com",
                company_logo_url="https://www.google.com/s2/favicons?domain=monzo.com&sz=128",
                location="London, United Kingdom",
                country="United Kingdom",
                city="London",
                work_mode="HYBRID",
                employment_type="Full-time",
                experience_level="Mid Level",
                salary="£75,000 - £95,000 / year",
                description="Join Monzo's core banking engineering team building resilient distributed microservices in Python and Go, backed by Cassandra and Kafka.",
                url="https://monzo.com/careers",
                source_url="https://monzo.com/careers",
                apply_url="https://job-boards.greenhouse.io/monzo",
                posted_date="4 hours ago",
                source="Greenhouse (Monzo)",
                source_job_id="monzo_swe_103",
                skills=["Python", "Go", "SQL", "Microservices", "Docker", "Kubernetes", "Kafka"],
                is_external_application=True
            ),
            # 4. Bloomberg
            JobListing(
                id="uk_swe_104",
                title="Senior Python & Data Infrastructure Engineer",
                company="Bloomberg",
                company_domain="bloomberg.com",
                company_logo_url="https://www.google.com/s2/favicons?domain=bloomberg.com&sz=128",
                location="London, United Kingdom",
                country="United Kingdom",
                city="London",
                work_mode="HYBRID",
                employment_type="Full-time",
                experience_level="Senior Level",
                salary="£95,000 - £135,000 / year",
                description="Bloomberg London is hiring an experienced Python engineer to build real-time financial market data feeds, distributed message buses, and asynchronous analytics pipelines.",
                url="https://bloomberg.com/careers",
                source_url="https://bloomberg.com/careers",
                apply_url="https://bloomberg.com/careers",
                posted_date="5 hours ago",
                source="Bloomberg Careers",
                source_job_id="bbg_swe_104",
                skills=["Python", "FastAPI", "AsyncIO", "PostgreSQL", "Kafka", "Docker", "C++"],
                is_external_application=True
            ),
            # 5. Stripe
            JobListing(
                id="uk_swe_105",
                title="Senior Software Engineer - Payments Backend",
                company="Stripe",
                company_domain="stripe.com",
                company_logo_url="https://www.google.com/s2/favicons?domain=stripe.com&sz=128",
                location="Remote, United Kingdom",
                country="United Kingdom",
                city="Remote",
                work_mode="REMOTE",
                employment_type="Full-time",
                experience_level="Senior Level",
                salary="£100,000 - £140,000 / year",
                description="Stripe is seeking a Remote Backend Engineer in the UK to design robust payments APIs, transaction ledgering, and high-availability distributed infrastructure.",
                url="https://stripe.com/careers",
                source_url="https://stripe.com/careers",
                apply_url="https://stripe.com/careers",
                posted_date="1 day ago",
                source="Stripe Careers",
                source_job_id="stripe_swe_105",
                skills=["Python", "Ruby", "PostgreSQL", "Distributed Systems", "AWS", "REST API", "Microservices"],
                is_external_application=True
            ),
            # 6. Deliveroo
            JobListing(
                id="uk_swe_106",
                title="Junior Python Software Engineer (0-1 Years)",
                company="Deliveroo",
                company_domain="deliveroo.co.uk",
                company_logo_url="https://www.google.com/s2/favicons?domain=deliveroo.co.uk&sz=128",
                location="London, United Kingdom",
                country="United Kingdom",
                city="London",
                work_mode="HYBRID",
                employment_type="Full-time",
                experience_level="Entry Level",
                salary="£45,000 - £60,000 / year",
                description="Deliveroo London is hiring an Entry Level / Graduate Software Engineer (0-1 years exp) passionate about Python, PostgreSQL, and building reliable microservices.",
                url="https://deliveroo.co.uk/careers",
                source_url="https://deliveroo.co.uk/careers",
                apply_url="https://deliveroo.co.uk/careers",
                posted_date="1 day ago",
                source="Deliveroo Careers",
                source_job_id="deliv_swe_106",
                skills=["Python", "SQL", "PostgreSQL", "FastAPI", "Git", "REST API"],
                is_external_application=True
            ),
            # 7. Cloudflare
            JobListing(
                id="uk_swe_107",
                title="Systems & Backend Engineer (Python / Rust)",
                company="Cloudflare",
                company_domain="cloudflare.com",
                company_logo_url="https://www.google.com/s2/favicons?domain=cloudflare.com&sz=128",
                location="London, United Kingdom",
                country="United Kingdom",
                city="London",
                work_mode="HYBRID",
                employment_type="Full-time",
                experience_level="Mid Level",
                salary="£80,000 - £110,000 / year",
                description="Cloudflare is hiring a Systems Engineer to scale edge network services, real-time analytics collectors, and API control planes in Python and Rust.",
                url="https://cloudflare.com/careers",
                source_url="https://cloudflare.com/careers",
                apply_url="https://job-boards.greenhouse.io/cloudflare",
                posted_date="2 days ago",
                source="Greenhouse (Cloudflare)",
                source_job_id="cf_swe_107",
                skills=["Python", "Rust", "Linux", "Docker", "Kubernetes", "PostgreSQL", "REST API"],
                is_external_application=True
            ),
            # 8. BBC
            JobListing(
                id="uk_swe_108",
                title="Full Stack Software Engineer (Python & React)",
                company="BBC",
                company_domain="bbc.co.uk",
                company_logo_url="https://www.google.com/s2/favicons?domain=bbc.co.uk&sz=128",
                location="Manchester, United Kingdom",
                country="United Kingdom",
                city="Manchester",
                work_mode="HYBRID",
                employment_type="Full-time",
                experience_level="Mid Level",
                salary="£55,000 - £75,000 / year",
                description="BBC Digital Products in MediaCityUK Manchester is hiring a Software Engineer to develop content authoring services and audience APIs using Python, FastAPI, React, and AWS.",
                url="https://bbc.co.uk/careers",
                source_url="https://bbc.co.uk/careers",
                apply_url="https://careers.bbc.co.uk",
                posted_date="2 days ago",
                source="BBC Careers",
                source_job_id="bbc_swe_108",
                skills=["Python", "React", "TypeScript", "FastAPI", "AWS", "SQL", "CI/CD"],
                is_external_application=True
            ),
            # 9. Amazon
            JobListing(
                id="uk_swe_109",
                title="Software Development Engineer - AWS Cloud",
                company="Amazon",
                company_domain="amazon.com",
                company_logo_url="https://www.google.com/s2/favicons?domain=amazon.com&sz=128",
                location="Cambridge, United Kingdom",
                country="United Kingdom",
                city="Cambridge",
                work_mode="HYBRID",
                employment_type="Full-time",
                experience_level="Mid Level",
                salary="£80,000 - £110,000 / year",
                description="Amazon Development Centre in Cambridge is hiring a Software Development Engineer to build distributed cloud orchestration systems using Python, AWS, and DynamoDB.",
                url="https://amazon.jobs",
                source_url="https://amazon.jobs",
                apply_url="https://amazon.jobs",
                posted_date="3 days ago",
                source="Amazon Jobs",
                source_job_id="amz_cam_109",
                skills=["Python", "AWS", "SQL", "Docker", "Distributed Systems", "Java"],
                is_external_application=True
            ),
            # 10. Snyk
            JobListing(
                id="uk_swe_110",
                title="Security & Platform Software Engineer",
                company="Snyk",
                company_domain="snyk.io",
                company_logo_url="https://www.google.com/s2/favicons?domain=snyk.io&sz=128",
                location="London, United Kingdom",
                country="United Kingdom",
                city="London",
                work_mode="HYBRID",
                employment_type="Full-time",
                experience_level="Mid Level",
                salary="£80,000 - £105,000 / year",
                description="Snyk is hiring a Software Engineer in London to build developer security platforms, vulnerability scanners, and scalable ingestion services using Python and TypeScript.",
                url="https://snyk.io/careers",
                source_url="https://snyk.io/careers",
                apply_url="https://snyk.io/careers",
                posted_date="3 days ago",
                source="Snyk Careers",
                source_job_id="snyk_swe_110",
                skills=["Python", "TypeScript", "Docker", "Kubernetes", "PostgreSQL", "AWS", "Git"],
                is_external_application=True
            )
        ]
        return catalog
